version: '2'

services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somedatabase
       MYSQL_DATABASE: argue
       MYSQL_USER: homestead
       MYSQL_PASSWORD: secret

   redis:
     image: redis
     restart: always

   memcached:
     image: memcached
     restart: always

   arguesecure:
     depends_on:
       - db
       - redis
       - memcached
     image: etews/arguesecure
     ports:
       - "8000:80"
       - "3002:3002"
     restart: always
     environment:
       DB_HOST: db
       REDIS_HOST: redis
       WEBSOCKET_IP: "http://localhost"
       MEMCACHED_HOST: "memcached"

volumes:
    db_data:
